### ISSUE TITLE
Wishlist: Reduce HTTP Requests to 1

### ISSUE THREAD

**Issue by jrchamp** [ncstate/utility-bar#17]
With the rewrite, there are only three HTTP requests being made when showBrick is enabled. So let's pose the question: Can we get down to 1?

- Does main.js need to be separate from ub-php.js?
- Can we use a base64 data URI for the NC State brick instead? (This would match all other images in the utility bar).

I'm very grateful for work that has been done - the new ub-php.js has a noticeable improvement in load time for me - my hope is to continue to reduce the impact of this ubiquitous script. Thank you again for your consideration.

**Comment by apmatthews** [comment]
Yes, I'd love to reduce it to 1 HTTP request. I'd still like to get what has been done so far deployed first, but this is definitely next on the TODO list. Specifics:

- No, main.js definitely doesn't need to be separate and I think we should try to eliminate it. I just left it alone during the rewrite because it was small, had no bugs, and didn't create any maintainability issues like the rest of the files did.
- Yes, the brick should be changed to a base64 data URI.

Glad to hear about the improvement!
