### ISSUE TITLE
Utility Bar Does Not Load (iOS 9.3.5)

### ISSUE THREAD

**Issue by jrchamp** [ncstate/utility-bar#19]
Tested on an iPad using Safari and Chrome 60. Updating to iOS 10.3.3 resolved the issue.

I'm not sure why it did not load, but I wanted to give you a heads up in case it is affecting other things.

**Comment by apmatthews** [comment]
Thanks! Interesting timing. We had received a few reports of the bar not loading as well, so I was just working on a fix. Turns out we were using Object.assign, which is unsupported in IE 11 and probably other older clients. I've added a polyfill in e7950ad595aae94e59874aac433c589afb1f652f that should take care of it. The update is live on cdn.ncsu.edu now.

**Comment by jrchamp** [comment]
iOS 9 appears to have support for Object.assign, so I don't think that's it. Unfortunately, now that I've updated I can't test again with that iPad.

**Comment by apmatthews** [comment]
You're right, it was something else. I had an iOS 9 device laying around and was able to pin it down. The fix is in 7b06598912a933728dd9880b40a280ed5fdbb795 and has been applied to cdn.ncsu.edu.

**Comment by jrchamp** [comment]
7b06598 seems straightforward, but options do not appear to be working any more. showBrick and color selection are having no effect.

**Comment by apmatthews** [comment]
😮 

We'll take this one a little slower. I've pushed another fix in b4ca9e1f11f16f240766227212e009514c497666. Would love to get another pair of eyes on it before I push it to cdn!

**Comment by apmatthews** [comment]
@jrchamp I went ahead and updated cdn.ncsu.edu since it's after hours, the bug affects live sites, and you may not see this until tomorrow. I got some others here in the office to test though. We pulled it up on as many devices as we could find and it seems to be working again, but let me know if you find any issues!

**Comment by jrchamp** [comment]
Seems like a success! The options appear to be working again. Have a nice evening.
